apiVersion: v1
kind: Namespace
metadata:
  labels:
    kubernetes.io/metadata.name: openshift-local-storage
    openshift.io/cluster-monitoring: "true"
  name: openshift-local-storage
spec:
  finalizers:
  - kubernetes
