apiVersion: local.storage.openshift.io/v1alpha1
kind: LocalVolumeSet
metadata:
  finalizers:
    - storage.openshift.com/local-volume-protection
  name: localblock
  namespace: openshift-local-storage
spec:
  deviceInclusionSpec:
    deviceTypes:
      - disk
      - part
    minSize: 100Gi
  nodeSelector:
    nodeSelectorTerms:
      - matchExpressions:
          - key: cluster.ocs.openshift.io/openshift-storage
            operator: Exists
  storageClassName: localblock
  tolerations:
    - effect: NoSchedule
      key: node.ocs.openshift.io/storage
      operator: Equal
      value: 'true'
  volumeMode: Block
