apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: odf-operator
  namespace: openshift-storage
  labels:
    operators.coreos.com/odf-operator.openshift-storage: ""
spec:
  channel: "stable-4.10" 
  installPlanApproval: Automatic
  name: odf-operator
  source: redhat-operators  
  sourceNamespace: openshift-marketplace
